---
- name: Update apt cache and upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Set GPU memory split to 16 MB
  lineinfile:
    path: /boot/config.txt
    line: 'gpu_mem=16'
    create: yes

- name: Add cgroup directives to boot commandline config
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '((.)+?)(\scgroup_\w+=\w+)*$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: yes

# - name: Set hostname to inventory hostname
#   hostname: name={{ inventory_hostname }}

# - name: Change hostname
#   lineinfile:
#     path: /etc/hosts
#     line: "127.0.0.1 {{ inventory_hostname }}"

- name: Reboot the node
  reboot:
